export const GET_CONTACTS_LOAD = "GET_CONTACTS_LOAD"
export const GET_CONTACTS_SUCCES = "GET_CONTACTS_SUCCES"
export const GET_CONTACTS_FAILED = "GET_CONTACTS_FAILED"
export const GET_ONE_CONTACT    = "GET_ONE_CONTACT "